import { Link } from "react-router-dom";

function Section({ title, children }) {
  return (
    <section className="si-card p-5">
      <h2 className="si-card-h">{title}</h2>
      <div className="text-sm text-slate-300 space-y-2 leading-relaxed">{children}</div>
    </section>
  );
}

export default function UserGuide() {
  return (
    <div className="max-w-3xl space-y-4">
      <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3">
        <div>
          <h1 className="si-h1">User Guide</h1>
          <p className="si-lede">Investigator reference for the SignalSentry console. Heuristic findings only.</p>
        </div>
        <Link to="/dashboard" className="si-btn shrink-0 self-start">
          Back to Command Center
        </Link>
      </div>

      <Section title="Start here">
        <p>
          Open <Link className="text-soc-cyan hover:underline" to="/dashboard">Launch Dashboard</Link> (Command Center).
          Click <strong className="text-slate-100 font-medium">Load synthetic dataset</strong> (seed 42).
        </p>
        <p className="text-soc-muted text-[13px]">
          The demo set is self-generated by this project. It is not a live ISP feed.
        </p>
      </Section>

      <Section title="Attack Explorer">
        <p>Start with one filter. Combine filters only when you want to narrow results further.</p>
        <ul className="text-[13px] text-soc-muted space-y-1 list-disc pl-4">
          <li>
            <span className="text-slate-300">Source IP / Dest IP</span> — exact address (e.g.{" "}
            <span className="font-mono">10.50.1.10</span>).
          </li>
          <li>
            <span className="text-slate-300">IP range (CIDR)</span> — a network, e.g.{" "}
            <span className="font-mono">10.50.1.0/24</span>.
          </li>
          <li>
            <span className="text-slate-300">Attack type, Verdict, Severity</span> — family, ATTEMPT/CONFIRMED/UNKNOWN,
            and severity.
          </li>
        </ul>
        <p>Click a detection row to open incident evidence.</p>
      </Section>

      <Section title="IP investigation">
        <p>
          Query a single IPv4 or a CIDR against ingested events. Demo attacker range:{" "}
          <span className="font-mono text-soc-cyan">10.50.1.0/24</span>.
        </p>
        <p className="text-[13px] font-mono text-soc-muted">
          Examples: 10.50.1.10 · 10.50.1.0/24
        </p>
      </Section>

      <Section title="IPDR and PCAP">
        <p>
          <strong className="text-slate-100 font-medium">IPDR Explorer</strong> — upload IPDR-like CSV/JSON (column
          aliases such as timestamp, src_ip, dst_ip, url/host/path).
        </p>
        <p>
          <strong className="text-slate-100 font-medium">PCAP Analyzer</strong> — upload PCAP/PCAPNG. Events are derived
          from packet metadata, then the same detection/correlation pipeline runs.
        </p>
        <p className="text-[13px] text-soc-muted">
          Encrypted HTTPS payloads are not decrypted. Missing paths are not invented.
        </p>
      </Section>

      <Section title="Verdicts">
        <ul className="text-[13px] space-y-1.5">
          <li>
            <span className="font-mono text-amber-200/90">ATTEMPT</span> — suspicious evidence without enough correlated
            evidence for confirmation.
          </li>
          <li>
            <span className="font-mono text-red-300">CONFIRMED</span> — correlated evidence meets this project’s confirmation
            heuristics. Not proof of compromise. Not a URL-only regex match.
          </li>
          <li>
            <span className="font-mono text-slate-300">UNKNOWN</span> — insufficient or uncertain evidence (including
            incomplete HTTP).
          </li>
        </ul>
      </Section>

      <Section title="Typical investigation workflow">
        <p className="font-mono text-[13px] text-soc-cyan tracking-wide">
          INGEST → NORMALIZE → DETECT → CORRELATE → INVESTIGATE → EXPORT
        </p>
      </Section>

      <Section title="Reports">
        <p>
          CSV and JSON downloads on the Reports page use the <strong className="text-slate-100 font-medium">current
          filters</strong> (same fields as Attack Explorer). Heuristic investigation output, not a precision/recall
          scorecard.
        </p>
      </Section>
    </div>
  );
}
